"""Revision 2

Revision ID: 8616f4eceeea
Revises: a588f945eef7
Create Date: 2024-01-09 10:20:31.588968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8616f4eceeea'
down_revision = 'a588f945eef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
